name:                destiny-gear-optimizer
version:             0.1.0.0
github:              "KaneTW/destiny-gear-optimizer"
license:             BSD3
author:              "David Kraeutmann"
maintainer:          "kane@kane.cx"
copyright:           "2020 David Kraeutmann"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/KaneTW/destiny-gear-optimizer#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- lens
- generic-lens
- vector
- stm
- monad-parallel
- ttrie
- hashable
- vector-instances
- cereal
- bytestring
- cereal-vector
- haskeline
- directory
- deepseq

default-extensions:
- AllowAmbiguousTypes
- TypeInType
- GADTs
- FlexibleContexts
- TypeApplications
- UndecidableInstances
- GeneralizedNewtypeDeriving
- NoMonoLocalBinds

ghc-options:
- -O2
- -funbox-strict-fields

library:
  source-dirs: src

executables:
  destiny-gear-optimizer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - destiny-gear-optimizer

tests:
  destiny-gear-optimizer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - destiny-gear-optimizer
